[package]
name = "repo-dump"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.4"
glob = "0.3"
anyhow = "1.0"
thiserror = "1.0"
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
