name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: "repo-dump-linux-x86_64.deb"
            package_type: "deb"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install dependencies
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential pkg-config libssl-dev
          fi
      - name: Build
        run: cargo build --release
      - name: Create package
        run: |
          if [ "${{ matrix.package_type }}" = "deb" ]; then
            # Create Debian package
            mkdir -p debian/DEBIAN
            # Extract version from tag (remove 'v' prefix)
            VERSION=${GITHUB_REF#refs/tags/}
            VERSION=${VERSION#v}
            echo "Package: repo-dump" > debian/DEBIAN/control
            echo "Version: $VERSION" >> debian/DEBIAN/control
            echo "Architecture: amd64" >> debian/DEBIAN/control
            echo "Maintainer: ngochai285nd@gmail.com" >> debian/DEBIAN/control
            echo "Description: A tool to dump the source code of a repository" >> debian/DEBIAN/control
            echo "Homepage: https://github.com/haiphamcoder/repo-dump" >> debian/DEBIAN/control
            mkdir -p debian/usr/local/bin
            cp target/release/repo-dump debian/usr/local/bin/
            dpkg-deb --build debian ${{ matrix.artifact_name }}
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}
  
  